// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.1
// source: adinfo/v1/adinfo.proto

package adinfov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AdInfoResolveRequested is used when a service needs to resolve ad information by token.
// This message is designed for RabbitMQ request/reply or async workflows.
type AdInfoResolveRequested struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Token     string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *AdInfoResolveRequested) Reset() {
	*x = AdInfoResolveRequested{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adinfo_v1_adinfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdInfoResolveRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdInfoResolveRequested) ProtoMessage() {}

func (x *AdInfoResolveRequested) ProtoReflect() protoreflect.Message {
	mi := &file_adinfo_v1_adinfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdInfoResolveRequested.ProtoReflect.Descriptor instead.
func (*AdInfoResolveRequested) Descriptor() ([]byte, []int) {
	return file_adinfo_v1_adinfo_proto_rawDescGZIP(), []int{0}
}

func (x *AdInfoResolveRequested) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AdInfoResolveRequested) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// AdInfoResolved is published when ad information has been resolved successfully.
type AdInfoResolved struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string  `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Data      *AdInfo `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *AdInfoResolved) Reset() {
	*x = AdInfoResolved{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adinfo_v1_adinfo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdInfoResolved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdInfoResolved) ProtoMessage() {}

func (x *AdInfoResolved) ProtoReflect() protoreflect.Message {
	mi := &file_adinfo_v1_adinfo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdInfoResolved.ProtoReflect.Descriptor instead.
func (*AdInfoResolved) Descriptor() ([]byte, []int) {
	return file_adinfo_v1_adinfo_proto_rawDescGZIP(), []int{1}
}

func (x *AdInfoResolved) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AdInfoResolved) GetData() *AdInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// AdInfoResolveFailed is published when resolving ad information fails.
type AdInfoResolveFailed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Token     string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Reason    string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *AdInfoResolveFailed) Reset() {
	*x = AdInfoResolveFailed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adinfo_v1_adinfo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdInfoResolveFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdInfoResolveFailed) ProtoMessage() {}

func (x *AdInfoResolveFailed) ProtoReflect() protoreflect.Message {
	mi := &file_adinfo_v1_adinfo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdInfoResolveFailed.ProtoReflect.Descriptor instead.
func (*AdInfoResolveFailed) Descriptor() ([]byte, []int) {
	return file_adinfo_v1_adinfo_proto_rawDescGZIP(), []int{2}
}

func (x *AdInfoResolveFailed) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AdInfoResolveFailed) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AdInfoResolveFailed) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// AdInfo represents ad/campaign data exchanged between services.
type AdInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token          string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Url            string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Target         int32    `protobuf:"varint,3,opt,name=target,proto3" json:"target,omitempty"`
	Status         bool     `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	AdminTest      bool     `protobuf:"varint,5,opt,name=admin_test,json=adminTest,proto3" json:"admin_test,omitempty"`
	Tracker        bool     `protobuf:"varint,6,opt,name=tracker,proto3" json:"tracker,omitempty"`
	TrackerName    string   `protobuf:"bytes,7,opt,name=tracker_name,json=trackerName,proto3" json:"tracker_name,omitempty"`
	TrackerChannel string   `protobuf:"bytes,8,opt,name=tracker_channel,json=trackerChannel,proto3" json:"tracker_channel,omitempty"`
	Industry       []string `protobuf:"bytes,9,rep,name=industry,proto3" json:"industry,omitempty"`
	AuthLogin      bool     `protobuf:"varint,10,opt,name=auth_login,json=authLogin,proto3" json:"auth_login,omitempty"`
	EncryptionKey  string   `protobuf:"bytes,11,opt,name=encryption_key,json=encryptionKey,proto3" json:"encryption_key,omitempty"`
}

func (x *AdInfo) Reset() {
	*x = AdInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adinfo_v1_adinfo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdInfo) ProtoMessage() {}

func (x *AdInfo) ProtoReflect() protoreflect.Message {
	mi := &file_adinfo_v1_adinfo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdInfo.ProtoReflect.Descriptor instead.
func (*AdInfo) Descriptor() ([]byte, []int) {
	return file_adinfo_v1_adinfo_proto_rawDescGZIP(), []int{3}
}

func (x *AdInfo) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AdInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AdInfo) GetTarget() int32 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *AdInfo) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *AdInfo) GetAdminTest() bool {
	if x != nil {
		return x.AdminTest
	}
	return false
}

func (x *AdInfo) GetTracker() bool {
	if x != nil {
		return x.Tracker
	}
	return false
}

func (x *AdInfo) GetTrackerName() string {
	if x != nil {
		return x.TrackerName
	}
	return ""
}

func (x *AdInfo) GetTrackerChannel() string {
	if x != nil {
		return x.TrackerChannel
	}
	return ""
}

func (x *AdInfo) GetIndustry() []string {
	if x != nil {
		return x.Industry
	}
	return nil
}

func (x *AdInfo) GetAuthLogin() bool {
	if x != nil {
		return x.AuthLogin
	}
	return false
}

func (x *AdInfo) GetEncryptionKey() string {
	if x != nil {
		return x.EncryptionKey
	}
	return ""
}

var File_adinfo_v1_adinfo_proto protoreflect.FileDescriptor

var file_adinfo_v1_adinfo_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x64, 0x69, 0x6e, 0x66, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x64, 0x69, 0x6e,
	0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x61, 0x64, 0x69, 0x6e, 0x66, 0x6f,
	0x2e, 0x76, 0x31, 0x22, 0x4d, 0x0a, 0x16, 0x41, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x6f, 0x6c, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x22, 0x56, 0x0a, 0x0e, 0x41, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x6f,
	0x6c, 0x76, 0x65, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x61, 0x64, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x62, 0x0a, 0x13, 0x41, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x46, 0x61, 0x69, 0x6c, 0x65,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0xc7,
	0x02, 0x0a, 0x06, 0x41, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x54, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x72,
	0x61, 0x63, 0x6b, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x0a,
	0x0f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x64, 0x75, 0x73, 0x74,
	0x72, 0x79, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x64, 0x75, 0x73, 0x74,
	0x72, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x61, 0x75, 0x74, 0x68, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x65, 0x6e, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x68, 0x72, 0x64, 0x61, 0x64, 0x2d, 0x6d,
	0x61, 0x73, 0x6f, 0x75, 0x6d, 0x69, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73,
	0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2f, 0x61, 0x64, 0x69, 0x6e, 0x66, 0x6f,
	0x2f, 0x76, 0x31, 0x3b, 0x61, 0x64, 0x69, 0x6e, 0x66, 0x6f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_adinfo_v1_adinfo_proto_rawDescOnce sync.Once
	file_adinfo_v1_adinfo_proto_rawDescData = file_adinfo_v1_adinfo_proto_rawDesc
)

func file_adinfo_v1_adinfo_proto_rawDescGZIP() []byte {
	file_adinfo_v1_adinfo_proto_rawDescOnce.Do(func() {
		file_adinfo_v1_adinfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_adinfo_v1_adinfo_proto_rawDescData)
	})
	return file_adinfo_v1_adinfo_proto_rawDescData
}

var file_adinfo_v1_adinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_adinfo_v1_adinfo_proto_goTypes = []interface{}{
	(*AdInfoResolveRequested)(nil), // 0: adinfo.v1.AdInfoResolveRequested
	(*AdInfoResolved)(nil),         // 1: adinfo.v1.AdInfoResolved
	(*AdInfoResolveFailed)(nil),    // 2: adinfo.v1.AdInfoResolveFailed
	(*AdInfo)(nil),                 // 3: adinfo.v1.AdInfo
}
var file_adinfo_v1_adinfo_proto_depIdxs = []int32{
	3, // 0: adinfo.v1.AdInfoResolved.data:type_name -> adinfo.v1.AdInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_adinfo_v1_adinfo_proto_init() }
func file_adinfo_v1_adinfo_proto_init() {
	if File_adinfo_v1_adinfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_adinfo_v1_adinfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdInfoResolveRequested); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adinfo_v1_adinfo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdInfoResolved); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adinfo_v1_adinfo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdInfoResolveFailed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adinfo_v1_adinfo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_adinfo_v1_adinfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_adinfo_v1_adinfo_proto_goTypes,
		DependencyIndexes: file_adinfo_v1_adinfo_proto_depIdxs,
		MessageInfos:      file_adinfo_v1_adinfo_proto_msgTypes,
	}.Build()
	File_adinfo_v1_adinfo_proto = out.File
	file_adinfo_v1_adinfo_proto_rawDesc = nil
	file_adinfo_v1_adinfo_proto_goTypes = nil
	file_adinfo_v1_adinfo_proto_depIdxs = nil
}
