// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: outbox/outbox.proto

package outboxpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message status enum
type MessageStatus int32

const (
	MessageStatus_MESSAGE_STATUS_UNSPECIFIED MessageStatus = 0
	MessageStatus_MESSAGE_STATUS_PENDING     MessageStatus = 1
	MessageStatus_MESSAGE_STATUS_PUBLISHED   MessageStatus = 2
	MessageStatus_MESSAGE_STATUS_FAILED      MessageStatus = 3
)

// Enum value maps for MessageStatus.
var (
	MessageStatus_name = map[int32]string{
		0: "MESSAGE_STATUS_UNSPECIFIED",
		1: "MESSAGE_STATUS_PENDING",
		2: "MESSAGE_STATUS_PUBLISHED",
		3: "MESSAGE_STATUS_FAILED",
	}
	MessageStatus_value = map[string]int32{
		"MESSAGE_STATUS_UNSPECIFIED": 0,
		"MESSAGE_STATUS_PENDING":     1,
		"MESSAGE_STATUS_PUBLISHED":   2,
		"MESSAGE_STATUS_FAILED":      3,
	}
)

func (x MessageStatus) Enum() *MessageStatus {
	p := new(MessageStatus)
	*p = x
	return p
}

func (x MessageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_outbox_outbox_proto_enumTypes[0].Descriptor()
}

func (MessageStatus) Type() protoreflect.EnumType {
	return &file_outbox_outbox_proto_enumTypes[0]
}

func (x MessageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageStatus.Descriptor instead.
func (MessageStatus) EnumDescriptor() ([]byte, []int) {
	return file_outbox_outbox_proto_rawDescGZIP(), []int{0}
}

// OutboxMessage represents a message in the outbox
type OutboxMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AggregateId   string                 `protobuf:"bytes,2,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	AggregateType string                 `protobuf:"bytes,3,opt,name=aggregate_type,json=aggregateType,proto3" json:"aggregate_type,omitempty"`
	EventType     string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Status        MessageStatus          `protobuf:"varint,6,opt,name=status,proto3,enum=outbox.MessageStatus" json:"status,omitempty"`
	RetryCount    int32                  `protobuf:"varint,7,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`        // Unix timestamp
	UpdatedAt     int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`        // Unix timestamp
	PublishedAt   int64                  `protobuf:"varint,10,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"` // Unix timestamp (0 if not published)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboxMessage) Reset() {
	*x = OutboxMessage{}
	mi := &file_outbox_outbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboxMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboxMessage) ProtoMessage() {}

func (x *OutboxMessage) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_outbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboxMessage.ProtoReflect.Descriptor instead.
func (*OutboxMessage) Descriptor() ([]byte, []int) {
	return file_outbox_outbox_proto_rawDescGZIP(), []int{0}
}

func (x *OutboxMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OutboxMessage) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *OutboxMessage) GetAggregateType() string {
	if x != nil {
		return x.AggregateType
	}
	return ""
}

func (x *OutboxMessage) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *OutboxMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *OutboxMessage) GetStatus() MessageStatus {
	if x != nil {
		return x.Status
	}
	return MessageStatus_MESSAGE_STATUS_UNSPECIFIED
}

func (x *OutboxMessage) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *OutboxMessage) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *OutboxMessage) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *OutboxMessage) GetPublishedAt() int64 {
	if x != nil {
		return x.PublishedAt
	}
	return 0
}

// CreateMessageRequest for creating a new outbox message
type CreateMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateId   string                 `protobuf:"bytes,1,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	AggregateType string                 `protobuf:"bytes,2,opt,name=aggregate_type,json=aggregateType,proto3" json:"aggregate_type,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMessageRequest) Reset() {
	*x = CreateMessageRequest{}
	mi := &file_outbox_outbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMessageRequest) ProtoMessage() {}

func (x *CreateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_outbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMessageRequest.ProtoReflect.Descriptor instead.
func (*CreateMessageRequest) Descriptor() ([]byte, []int) {
	return file_outbox_outbox_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMessageRequest) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *CreateMessageRequest) GetAggregateType() string {
	if x != nil {
		return x.AggregateType
	}
	return ""
}

func (x *CreateMessageRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *CreateMessageRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// CreateMessageResponse returns the created message
type CreateMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *OutboxMessage         `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMessageResponse) Reset() {
	*x = CreateMessageResponse{}
	mi := &file_outbox_outbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMessageResponse) ProtoMessage() {}

func (x *CreateMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_outbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMessageResponse.ProtoReflect.Descriptor instead.
func (*CreateMessageResponse) Descriptor() ([]byte, []int) {
	return file_outbox_outbox_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMessageResponse) GetMessage() *OutboxMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

// GetMessageRequest for retrieving a message by ID
type GetMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageRequest) Reset() {
	*x = GetMessageRequest{}
	mi := &file_outbox_outbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageRequest) ProtoMessage() {}

func (x *GetMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_outbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageRequest.ProtoReflect.Descriptor instead.
func (*GetMessageRequest) Descriptor() ([]byte, []int) {
	return file_outbox_outbox_proto_rawDescGZIP(), []int{3}
}

func (x *GetMessageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetMessageResponse returns the message
type GetMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *OutboxMessage         `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageResponse) Reset() {
	*x = GetMessageResponse{}
	mi := &file_outbox_outbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageResponse) ProtoMessage() {}

func (x *GetMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_outbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageResponse.ProtoReflect.Descriptor instead.
func (*GetMessageResponse) Descriptor() ([]byte, []int) {
	return file_outbox_outbox_proto_rawDescGZIP(), []int{4}
}

func (x *GetMessageResponse) GetMessage() *OutboxMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

// ListPendingMessagesRequest for listing pending messages
type ListPendingMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"` // Maximum number of messages to return
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingMessagesRequest) Reset() {
	*x = ListPendingMessagesRequest{}
	mi := &file_outbox_outbox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingMessagesRequest) ProtoMessage() {}

func (x *ListPendingMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_outbox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListPendingMessagesRequest) Descriptor() ([]byte, []int) {
	return file_outbox_outbox_proto_rawDescGZIP(), []int{5}
}

func (x *ListPendingMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListPendingMessagesResponse returns a list of pending messages
type ListPendingMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*OutboxMessage       `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingMessagesResponse) Reset() {
	*x = ListPendingMessagesResponse{}
	mi := &file_outbox_outbox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingMessagesResponse) ProtoMessage() {}

func (x *ListPendingMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_outbox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListPendingMessagesResponse) Descriptor() ([]byte, []int) {
	return file_outbox_outbox_proto_rawDescGZIP(), []int{6}
}

func (x *ListPendingMessagesResponse) GetMessages() []*OutboxMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

// UpdateMessageStatusRequest for updating message status
type UpdateMessageStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        MessageStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=outbox.MessageStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessageStatusRequest) Reset() {
	*x = UpdateMessageStatusRequest{}
	mi := &file_outbox_outbox_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessageStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessageStatusRequest) ProtoMessage() {}

func (x *UpdateMessageStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_outbox_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessageStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateMessageStatusRequest) Descriptor() ([]byte, []int) {
	return file_outbox_outbox_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateMessageStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMessageStatusRequest) GetStatus() MessageStatus {
	if x != nil {
		return x.Status
	}
	return MessageStatus_MESSAGE_STATUS_UNSPECIFIED
}

// UpdateMessageStatusResponse confirms the update
type UpdateMessageStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessageStatusResponse) Reset() {
	*x = UpdateMessageStatusResponse{}
	mi := &file_outbox_outbox_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessageStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessageStatusResponse) ProtoMessage() {}

func (x *UpdateMessageStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_outbox_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessageStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateMessageStatusResponse) Descriptor() ([]byte, []int) {
	return file_outbox_outbox_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateMessageStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// DeleteMessageRequest for deleting a message
type DeleteMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageRequest) Reset() {
	*x = DeleteMessageRequest{}
	mi := &file_outbox_outbox_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageRequest) ProtoMessage() {}

func (x *DeleteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_outbox_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return file_outbox_outbox_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteMessageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteMessageResponse confirms the deletion
type DeleteMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageResponse) Reset() {
	*x = DeleteMessageResponse{}
	mi := &file_outbox_outbox_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageResponse) ProtoMessage() {}

func (x *DeleteMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_outbox_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageResponse.ProtoReflect.Descriptor instead.
func (*DeleteMessageResponse) Descriptor() ([]byte, []int) {
	return file_outbox_outbox_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_outbox_outbox_proto protoreflect.FileDescriptor

const file_outbox_outbox_proto_rawDesc = "" +
	"\n" +
	"\x13outbox/outbox.proto\x12\x06outbox\"\xd3\x02\n" +
	"\rOutboxMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\faggregate_id\x18\x02 \x01(\tR\vaggregateId\x12%\n" +
	"\x0eaggregate_type\x18\x03 \x01(\tR\raggregateType\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12-\n" +
	"\x06status\x18\x06 \x01(\x0e2\x15.outbox.MessageStatusR\x06status\x12\x1f\n" +
	"\vretry_count\x18\a \x01(\x05R\n" +
	"retryCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\x12!\n" +
	"\fpublished_at\x18\n" +
	" \x01(\x03R\vpublishedAt\"\x99\x01\n" +
	"\x14CreateMessageRequest\x12!\n" +
	"\faggregate_id\x18\x01 \x01(\tR\vaggregateId\x12%\n" +
	"\x0eaggregate_type\x18\x02 \x01(\tR\raggregateType\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"H\n" +
	"\x15CreateMessageResponse\x12/\n" +
	"\amessage\x18\x01 \x01(\v2\x15.outbox.OutboxMessageR\amessage\"#\n" +
	"\x11GetMessageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\x12GetMessageResponse\x12/\n" +
	"\amessage\x18\x01 \x01(\v2\x15.outbox.OutboxMessageR\amessage\"2\n" +
	"\x1aListPendingMessagesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"P\n" +
	"\x1bListPendingMessagesResponse\x121\n" +
	"\bmessages\x18\x01 \x03(\v2\x15.outbox.OutboxMessageR\bmessages\"[\n" +
	"\x1aUpdateMessageStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.outbox.MessageStatusR\x06status\"7\n" +
	"\x1bUpdateMessageStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"&\n" +
	"\x14DeleteMessageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x15DeleteMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*\x84\x01\n" +
	"\rMessageStatus\x12\x1e\n" +
	"\x1aMESSAGE_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16MESSAGE_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18MESSAGE_STATUS_PUBLISHED\x10\x02\x12\x19\n" +
	"\x15MESSAGE_STATUS_FAILED\x10\x032\xb0\x03\n" +
	"\rOutboxService\x12L\n" +
	"\rCreateMessage\x12\x1c.outbox.CreateMessageRequest\x1a\x1d.outbox.CreateMessageResponse\x12C\n" +
	"\n" +
	"GetMessage\x12\x19.outbox.GetMessageRequest\x1a\x1a.outbox.GetMessageResponse\x12^\n" +
	"\x13ListPendingMessages\x12\".outbox.ListPendingMessagesRequest\x1a#.outbox.ListPendingMessagesResponse\x12^\n" +
	"\x13UpdateMessageStatus\x12\".outbox.UpdateMessageStatusRequest\x1a#.outbox.UpdateMessageStatusResponse\x12L\n" +
	"\rDeleteMessage\x12\x1c.outbox.DeleteMessageRequest\x1a\x1d.outbox.DeleteMessageResponseB?Z=github.com/mehrdad-masoumi/contracts/contract/outbox;outboxpbb\x06proto3"

var (
	file_outbox_outbox_proto_rawDescOnce sync.Once
	file_outbox_outbox_proto_rawDescData []byte
)

func file_outbox_outbox_proto_rawDescGZIP() []byte {
	file_outbox_outbox_proto_rawDescOnce.Do(func() {
		file_outbox_outbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_outbox_outbox_proto_rawDesc), len(file_outbox_outbox_proto_rawDesc)))
	})
	return file_outbox_outbox_proto_rawDescData
}

var file_outbox_outbox_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_outbox_outbox_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_outbox_outbox_proto_goTypes = []any{
	(MessageStatus)(0),                  // 0: outbox.MessageStatus
	(*OutboxMessage)(nil),               // 1: outbox.OutboxMessage
	(*CreateMessageRequest)(nil),        // 2: outbox.CreateMessageRequest
	(*CreateMessageResponse)(nil),       // 3: outbox.CreateMessageResponse
	(*GetMessageRequest)(nil),           // 4: outbox.GetMessageRequest
	(*GetMessageResponse)(nil),          // 5: outbox.GetMessageResponse
	(*ListPendingMessagesRequest)(nil),  // 6: outbox.ListPendingMessagesRequest
	(*ListPendingMessagesResponse)(nil), // 7: outbox.ListPendingMessagesResponse
	(*UpdateMessageStatusRequest)(nil),  // 8: outbox.UpdateMessageStatusRequest
	(*UpdateMessageStatusResponse)(nil), // 9: outbox.UpdateMessageStatusResponse
	(*DeleteMessageRequest)(nil),        // 10: outbox.DeleteMessageRequest
	(*DeleteMessageResponse)(nil),       // 11: outbox.DeleteMessageResponse
}
var file_outbox_outbox_proto_depIdxs = []int32{
	0,  // 0: outbox.OutboxMessage.status:type_name -> outbox.MessageStatus
	1,  // 1: outbox.CreateMessageResponse.message:type_name -> outbox.OutboxMessage
	1,  // 2: outbox.GetMessageResponse.message:type_name -> outbox.OutboxMessage
	1,  // 3: outbox.ListPendingMessagesResponse.messages:type_name -> outbox.OutboxMessage
	0,  // 4: outbox.UpdateMessageStatusRequest.status:type_name -> outbox.MessageStatus
	2,  // 5: outbox.OutboxService.CreateMessage:input_type -> outbox.CreateMessageRequest
	4,  // 6: outbox.OutboxService.GetMessage:input_type -> outbox.GetMessageRequest
	6,  // 7: outbox.OutboxService.ListPendingMessages:input_type -> outbox.ListPendingMessagesRequest
	8,  // 8: outbox.OutboxService.UpdateMessageStatus:input_type -> outbox.UpdateMessageStatusRequest
	10, // 9: outbox.OutboxService.DeleteMessage:input_type -> outbox.DeleteMessageRequest
	3,  // 10: outbox.OutboxService.CreateMessage:output_type -> outbox.CreateMessageResponse
	5,  // 11: outbox.OutboxService.GetMessage:output_type -> outbox.GetMessageResponse
	7,  // 12: outbox.OutboxService.ListPendingMessages:output_type -> outbox.ListPendingMessagesResponse
	9,  // 13: outbox.OutboxService.UpdateMessageStatus:output_type -> outbox.UpdateMessageStatusResponse
	11, // 14: outbox.OutboxService.DeleteMessage:output_type -> outbox.DeleteMessageResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_outbox_outbox_proto_init() }
func file_outbox_outbox_proto_init() {
	if File_outbox_outbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_outbox_outbox_proto_rawDesc), len(file_outbox_outbox_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_outbox_outbox_proto_goTypes,
		DependencyIndexes: file_outbox_outbox_proto_depIdxs,
		EnumInfos:         file_outbox_outbox_proto_enumTypes,
		MessageInfos:      file_outbox_outbox_proto_msgTypes,
	}.Build()
	File_outbox_outbox_proto = out.File
	file_outbox_outbox_proto_goTypes = nil
	file_outbox_outbox_proto_depIdxs = nil
}
