// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: user/user.proto

package userpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User status enum
type StatusTypeUser int32

const (
	StatusTypeUser_STATUS_TYPE_USER_UNSPECIFIED StatusTypeUser = 0
	StatusTypeUser_STATUS_TYPE_USER_ACTIVE      StatusTypeUser = 1
	StatusTypeUser_STATUS_TYPE_USER_INACTIVE    StatusTypeUser = 2
	StatusTypeUser_STATUS_TYPE_USER_SUSPENDED   StatusTypeUser = 3
	StatusTypeUser_STATUS_TYPE_USER_DELETED     StatusTypeUser = 4
)

// Enum value maps for StatusTypeUser.
var (
	StatusTypeUser_name = map[int32]string{
		0: "STATUS_TYPE_USER_UNSPECIFIED",
		1: "STATUS_TYPE_USER_ACTIVE",
		2: "STATUS_TYPE_USER_INACTIVE",
		3: "STATUS_TYPE_USER_SUSPENDED",
		4: "STATUS_TYPE_USER_DELETED",
	}
	StatusTypeUser_value = map[string]int32{
		"STATUS_TYPE_USER_UNSPECIFIED": 0,
		"STATUS_TYPE_USER_ACTIVE":      1,
		"STATUS_TYPE_USER_INACTIVE":    2,
		"STATUS_TYPE_USER_SUSPENDED":   3,
		"STATUS_TYPE_USER_DELETED":     4,
	}
)

func (x StatusTypeUser) Enum() *StatusTypeUser {
	p := new(StatusTypeUser)
	*p = x
	return p
}

func (x StatusTypeUser) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusTypeUser) Descriptor() protoreflect.EnumDescriptor {
	return file_user_user_proto_enumTypes[0].Descriptor()
}

func (StatusTypeUser) Type() protoreflect.EnumType {
	return &file_user_user_proto_enumTypes[0]
}

func (x StatusTypeUser) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusTypeUser.Descriptor instead.
func (StatusTypeUser) EnumDescriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{0}
}

// User represents a user entity
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Status        StatusTypeUser         `protobuf:"varint,4,opt,name=status,proto3,enum=user.StatusTypeUser" json:"status,omitempty"`
	Verify        bool                   `protobuf:"varint,5,opt,name=verify,proto3" json:"verify,omitempty"`
	Profile       *Profile               `protobuf:"bytes,6,opt,name=profile,proto3" json:"profile,omitempty"`
	Roles         []*Role                `protobuf:"bytes,7,rep,name=roles,proto3" json:"roles,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *User) GetStatus() StatusTypeUser {
	if x != nil {
		return x.Status
	}
	return StatusTypeUser_STATUS_TYPE_USER_UNSPECIFIED
}

func (x *User) GetVerify() bool {
	if x != nil {
		return x.Verify
	}
	return false
}

func (x *User) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *User) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Profile represents user profile information
type Profile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`                              // optional
	FatherName    string                 `protobuf:"bytes,4,opt,name=father_name,json=fatherName,proto3" json:"father_name,omitempty"`    // optional
	NationalId    string                 `protobuf:"bytes,5,opt,name=national_id,json=nationalId,proto3" json:"national_id,omitempty"`    // optional
	Nationality   string                 `protobuf:"bytes,6,opt,name=nationality,proto3" json:"nationality,omitempty"`                    // optional
	CountryCode   string                 `protobuf:"bytes,7,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"` // optional
	Birthdate     string                 `protobuf:"bytes,8,opt,name=birthdate,proto3" json:"birthdate,omitempty"`                        // optional, ISO 8601 format string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *Profile) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Profile) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Profile) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Profile) GetFatherName() string {
	if x != nil {
		return x.FatherName
	}
	return ""
}

func (x *Profile) GetNationalId() string {
	if x != nil {
		return x.NationalId
	}
	return ""
}

func (x *Profile) GetNationality() string {
	if x != nil {
		return x.Nationality
	}
	return ""
}

func (x *Profile) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *Profile) GetBirthdate() string {
	if x != nil {
		return x.Birthdate
	}
	return ""
}

// Role represents a user role
type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"` // optional
	FullAccess    bool                   `protobuf:"varint,4,opt,name=full_access,json=fullAccess,proto3" json:"full_access,omitempty"`
	AdminAccess   bool                   `protobuf:"varint,5,opt,name=admin_access,json=adminAccess,proto3" json:"admin_access,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *Role) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Role) GetFullAccess() bool {
	if x != nil {
		return x.FullAccess
	}
	return false
}

func (x *Role) GetAdminAccess() bool {
	if x != nil {
		return x.AdminAccess
	}
	return false
}

func (x *Role) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Role) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// GetUserByIDRequest for retrieving a user by ID
type GetUserByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIDRequest) Reset() {
	*x = GetUserByIDRequest{}
	mi := &file_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIDRequest) ProtoMessage() {}

func (x *GetUserByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserByIDRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserByIDRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// GetUserByIDResponse returns the user data
type GetUserByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *User                  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIDResponse) Reset() {
	*x = GetUserByIDResponse{}
	mi := &file_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIDResponse) ProtoMessage() {}

func (x *GetUserByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIDResponse.ProtoReflect.Descriptor instead.
func (*GetUserByIDResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserByIDResponse) GetData() *User {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_user_user_proto protoreflect.FileDescriptor

const file_user_user_proto_rawDesc = "" +
	"\n" +
	"\x0fuser/user.proto\x12\x04user\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd6\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\x12,\n" +
	"\x06status\x18\x04 \x01(\x0e2\x14.user.StatusTypeUserR\x06status\x12\x16\n" +
	"\x06verify\x18\x05 \x01(\bR\x06verify\x12'\n" +
	"\aprofile\x18\x06 \x01(\v2\r.user.ProfileR\aprofile\x12 \n" +
	"\x05roles\x18\a \x03(\v2\n" +
	".user.RoleR\x05roles\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x82\x02\n" +
	"\aProfile\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x1f\n" +
	"\vfather_name\x18\x04 \x01(\tR\n" +
	"fatherName\x12\x1f\n" +
	"\vnational_id\x18\x05 \x01(\tR\n" +
	"nationalId\x12 \n" +
	"\vnationality\x18\x06 \x01(\tR\vnationality\x12!\n" +
	"\fcountry_code\x18\a \x01(\tR\vcountryCode\x12\x1c\n" +
	"\tbirthdate\x18\b \x01(\tR\tbirthdate\"\x86\x02\n" +
	"\x04Role\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vfull_access\x18\x04 \x01(\bR\n" +
	"fullAccess\x12!\n" +
	"\fadmin_access\x18\x05 \x01(\bR\vadminAccess\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"-\n" +
	"\x12GetUserByIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"5\n" +
	"\x13GetUserByIDResponse\x12\x1e\n" +
	"\x04data\x18\x01 \x01(\v2\n" +
	".user.UserR\x04data*\xac\x01\n" +
	"\x0eStatusTypeUser\x12 \n" +
	"\x1cSTATUS_TYPE_USER_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17STATUS_TYPE_USER_ACTIVE\x10\x01\x12\x1d\n" +
	"\x19STATUS_TYPE_USER_INACTIVE\x10\x02\x12\x1e\n" +
	"\x1aSTATUS_TYPE_USER_SUSPENDED\x10\x03\x12\x1c\n" +
	"\x18STATUS_TYPE_USER_DELETED\x10\x042Q\n" +
	"\vUserService\x12B\n" +
	"\vGetUserByID\x12\x18.user.GetUserByIDRequest\x1a\x19.user.GetUserByIDResponseBPZNgit.mtnirancell.ir/digital/yelloadwise/services/contracts/contract/user;userpbb\x06proto3"

var (
	file_user_user_proto_rawDescOnce sync.Once
	file_user_user_proto_rawDescData []byte
)

func file_user_user_proto_rawDescGZIP() []byte {
	file_user_user_proto_rawDescOnce.Do(func() {
		file_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_user_proto_rawDesc), len(file_user_user_proto_rawDesc)))
	})
	return file_user_user_proto_rawDescData
}

var file_user_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_user_user_proto_goTypes = []any{
	(StatusTypeUser)(0),           // 0: user.StatusTypeUser
	(*User)(nil),                  // 1: user.User
	(*Profile)(nil),               // 2: user.Profile
	(*Role)(nil),                  // 3: user.Role
	(*GetUserByIDRequest)(nil),    // 4: user.GetUserByIDRequest
	(*GetUserByIDResponse)(nil),   // 5: user.GetUserByIDResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_user_user_proto_depIdxs = []int32{
	0, // 0: user.User.status:type_name -> user.StatusTypeUser
	2, // 1: user.User.profile:type_name -> user.Profile
	3, // 2: user.User.roles:type_name -> user.Role
	6, // 3: user.User.created_at:type_name -> google.protobuf.Timestamp
	6, // 4: user.User.updated_at:type_name -> google.protobuf.Timestamp
	6, // 5: user.Role.created_at:type_name -> google.protobuf.Timestamp
	6, // 6: user.Role.updated_at:type_name -> google.protobuf.Timestamp
	1, // 7: user.GetUserByIDResponse.data:type_name -> user.User
	4, // 8: user.UserService.GetUserByID:input_type -> user.GetUserByIDRequest
	5, // 9: user.UserService.GetUserByID:output_type -> user.GetUserByIDResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_user_user_proto_init() }
func file_user_user_proto_init() {
	if File_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_user_proto_rawDesc), len(file_user_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_user_proto_goTypes,
		DependencyIndexes: file_user_user_proto_depIdxs,
		EnumInfos:         file_user_user_proto_enumTypes,
		MessageInfos:      file_user_user_proto_msgTypes,
	}.Build()
	File_user_user_proto = out.File
	file_user_user_proto_goTypes = nil
	file_user_user_proto_depIdxs = nil
}
