// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: campaign/campaign.proto

package campaignpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Campaign represents a campaign entity
type Campaign struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    int32                  `protobuf:"varint,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Target        int32                  `protobuf:"varint,3,opt,name=target,proto3" json:"target,omitempty"`
	Industry      int32                  `protobuf:"varint,4,opt,name=industry,proto3" json:"industry,omitempty"`
	Status        bool                   `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Campaign) Reset() {
	*x = Campaign{}
	mi := &file_campaign_campaign_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Campaign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Campaign) ProtoMessage() {}

func (x *Campaign) ProtoReflect() protoreflect.Message {
	mi := &file_campaign_campaign_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Campaign.ProtoReflect.Descriptor instead.
func (*Campaign) Descriptor() ([]byte, []int) {
	return file_campaign_campaign_proto_rawDescGZIP(), []int{0}
}

func (x *Campaign) GetCampaignId() int32 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

func (x *Campaign) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Campaign) GetTarget() int32 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *Campaign) GetIndustry() int32 {
	if x != nil {
		return x.Industry
	}
	return 0
}

func (x *Campaign) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// GetCampaignRequest for retrieving a campaign by ID
type GetCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    int32                  `protobuf:"varint,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCampaignRequest) Reset() {
	*x = GetCampaignRequest{}
	mi := &file_campaign_campaign_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignRequest) ProtoMessage() {}

func (x *GetCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaign_campaign_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignRequest.ProtoReflect.Descriptor instead.
func (*GetCampaignRequest) Descriptor() ([]byte, []int) {
	return file_campaign_campaign_proto_rawDescGZIP(), []int{1}
}

func (x *GetCampaignRequest) GetCampaignId() int32 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

// GetCampaignResponse returns the campaign
type GetCampaignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Campaign      *Campaign              `protobuf:"bytes,1,opt,name=campaign,proto3" json:"campaign,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCampaignResponse) Reset() {
	*x = GetCampaignResponse{}
	mi := &file_campaign_campaign_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCampaignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignResponse) ProtoMessage() {}

func (x *GetCampaignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campaign_campaign_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignResponse.ProtoReflect.Descriptor instead.
func (*GetCampaignResponse) Descriptor() ([]byte, []int) {
	return file_campaign_campaign_proto_rawDescGZIP(), []int{2}
}

func (x *GetCampaignResponse) GetCampaign() *Campaign {
	if x != nil {
		return x.Campaign
	}
	return nil
}

// CloseCampaignRequest for closing a campaign
type CloseCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    int32                  `protobuf:"varint,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseCampaignRequest) Reset() {
	*x = CloseCampaignRequest{}
	mi := &file_campaign_campaign_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseCampaignRequest) ProtoMessage() {}

func (x *CloseCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaign_campaign_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseCampaignRequest.ProtoReflect.Descriptor instead.
func (*CloseCampaignRequest) Descriptor() ([]byte, []int) {
	return file_campaign_campaign_proto_rawDescGZIP(), []int{3}
}

func (x *CloseCampaignRequest) GetCampaignId() int32 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

// CloseCampaignResponse confirms the campaign closure
type CloseCampaignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseCampaignResponse) Reset() {
	*x = CloseCampaignResponse{}
	mi := &file_campaign_campaign_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseCampaignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseCampaignResponse) ProtoMessage() {}

func (x *CloseCampaignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campaign_campaign_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseCampaignResponse.ProtoReflect.Descriptor instead.
func (*CloseCampaignResponse) Descriptor() ([]byte, []int) {
	return file_campaign_campaign_proto_rawDescGZIP(), []int{4}
}

func (x *CloseCampaignResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_campaign_campaign_proto protoreflect.FileDescriptor

const file_campaign_campaign_proto_rawDesc = "" +
	"\n" +
	"\x17campaign/campaign.proto\x12\bcampaign\"\x8d\x01\n" +
	"\bCampaign\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\x05R\n" +
	"campaignId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x16\n" +
	"\x06target\x18\x03 \x01(\x05R\x06target\x12\x1a\n" +
	"\bindustry\x18\x04 \x01(\x05R\bindustry\x12\x16\n" +
	"\x06status\x18\x05 \x01(\bR\x06status\"5\n" +
	"\x12GetCampaignRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\x05R\n" +
	"campaignId\"E\n" +
	"\x13GetCampaignResponse\x12.\n" +
	"\bcampaign\x18\x01 \x01(\v2\x12.campaign.CampaignR\bcampaign\"7\n" +
	"\x14CloseCampaignRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\x05R\n" +
	"campaignId\"1\n" +
	"\x15CloseCampaignResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xaf\x01\n" +
	"\x0fCampaignService\x12J\n" +
	"\vGetCampaign\x12\x1c.campaign.GetCampaignRequest\x1a\x1d.campaign.GetCampaignResponse\x12P\n" +
	"\rCloseCampaign\x12\x1e.campaign.CloseCampaignRequest\x1a\x1f.campaign.CloseCampaignResponseBCZAgithub.com/mehrdad-masoumi/contracts/contract/campaign;campaignpbb\x06proto3"

var (
	file_campaign_campaign_proto_rawDescOnce sync.Once
	file_campaign_campaign_proto_rawDescData []byte
)

func file_campaign_campaign_proto_rawDescGZIP() []byte {
	file_campaign_campaign_proto_rawDescOnce.Do(func() {
		file_campaign_campaign_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_campaign_campaign_proto_rawDesc), len(file_campaign_campaign_proto_rawDesc)))
	})
	return file_campaign_campaign_proto_rawDescData
}

var file_campaign_campaign_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_campaign_campaign_proto_goTypes = []any{
	(*Campaign)(nil),              // 0: campaign.Campaign
	(*GetCampaignRequest)(nil),    // 1: campaign.GetCampaignRequest
	(*GetCampaignResponse)(nil),   // 2: campaign.GetCampaignResponse
	(*CloseCampaignRequest)(nil),  // 3: campaign.CloseCampaignRequest
	(*CloseCampaignResponse)(nil), // 4: campaign.CloseCampaignResponse
}
var file_campaign_campaign_proto_depIdxs = []int32{
	0, // 0: campaign.GetCampaignResponse.campaign:type_name -> campaign.Campaign
	1, // 1: campaign.CampaignService.GetCampaign:input_type -> campaign.GetCampaignRequest
	3, // 2: campaign.CampaignService.CloseCampaign:input_type -> campaign.CloseCampaignRequest
	2, // 3: campaign.CampaignService.GetCampaign:output_type -> campaign.GetCampaignResponse
	4, // 4: campaign.CampaignService.CloseCampaign:output_type -> campaign.CloseCampaignResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_campaign_campaign_proto_init() }
func file_campaign_campaign_proto_init() {
	if File_campaign_campaign_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_campaign_campaign_proto_rawDesc), len(file_campaign_campaign_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_campaign_campaign_proto_goTypes,
		DependencyIndexes: file_campaign_campaign_proto_depIdxs,
		MessageInfos:      file_campaign_campaign_proto_msgTypes,
	}.Build()
	File_campaign_campaign_proto = out.File
	file_campaign_campaign_proto_goTypes = nil
	file_campaign_campaign_proto_depIdxs = nil
}
