// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.1
// source: tracker/v1/tracker.proto

package trackerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrackerPostbackEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClickEventId int64  `protobuf:"varint,1,opt,name=click_event_id,json=clickEventId,proto3" json:"click_event_id,omitempty"`
	TrackerToken string `protobuf:"bytes,2,opt,name=tracker_token,json=trackerToken,proto3" json:"tracker_token,omitempty"`
	Event        string `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"`
}

func (x *TrackerPostbackEvent) Reset() {
	*x = TrackerPostbackEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tracker_v1_tracker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackerPostbackEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackerPostbackEvent) ProtoMessage() {}

func (x *TrackerPostbackEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_v1_tracker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackerPostbackEvent.ProtoReflect.Descriptor instead.
func (*TrackerPostbackEvent) Descriptor() ([]byte, []int) {
	return file_tracker_v1_tracker_proto_rawDescGZIP(), []int{0}
}

func (x *TrackerPostbackEvent) GetClickEventId() int64 {
	if x != nil {
		return x.ClickEventId
	}
	return 0
}

func (x *TrackerPostbackEvent) GetTrackerToken() string {
	if x != nil {
		return x.TrackerToken
	}
	return ""
}

func (x *TrackerPostbackEvent) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

var File_tracker_v1_tracker_proto protoreflect.FileDescriptor

var file_tracker_v1_tracker_proto_rawDesc = []byte{
	0x0a, 0x18, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x72, 0x61,
	0x63, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x74, 0x72, 0x61, 0x63,
	0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x22, 0x77, 0x0a, 0x14, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65,
	0x72, 0x50, 0x6f, 0x73, 0x74, 0x62, 0x61, 0x63, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x24,
	0x0a, 0x0e, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x5f,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x72, 0x61,
	0x63, 0x6b, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x42,
	0x44, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x65,
	0x68, 0x72, 0x64, 0x61, 0x64, 0x2d, 0x6d, 0x61, 0x73, 0x6f, 0x75, 0x6d, 0x69, 0x2f, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x2f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x74, 0x72, 0x61, 0x63,
	0x6b, 0x65, 0x72, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tracker_v1_tracker_proto_rawDescOnce sync.Once
	file_tracker_v1_tracker_proto_rawDescData = file_tracker_v1_tracker_proto_rawDesc
)

func file_tracker_v1_tracker_proto_rawDescGZIP() []byte {
	file_tracker_v1_tracker_proto_rawDescOnce.Do(func() {
		file_tracker_v1_tracker_proto_rawDescData = protoimpl.X.CompressGZIP(file_tracker_v1_tracker_proto_rawDescData)
	})
	return file_tracker_v1_tracker_proto_rawDescData
}

var file_tracker_v1_tracker_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tracker_v1_tracker_proto_goTypes = []interface{}{
	(*TrackerPostbackEvent)(nil), // 0: tracker.v1.TrackerPostbackEvent
}
var file_tracker_v1_tracker_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tracker_v1_tracker_proto_init() }
func file_tracker_v1_tracker_proto_init() {
	if File_tracker_v1_tracker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tracker_v1_tracker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackerPostbackEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tracker_v1_tracker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tracker_v1_tracker_proto_goTypes,
		DependencyIndexes: file_tracker_v1_tracker_proto_depIdxs,
		MessageInfos:      file_tracker_v1_tracker_proto_msgTypes,
	}.Build()
	File_tracker_v1_tracker_proto = out.File
	file_tracker_v1_tracker_proto_rawDesc = nil
	file_tracker_v1_tracker_proto_goTypes = nil
	file_tracker_v1_tracker_proto_depIdxs = nil
}
